```{r}
counties <- readRDS("/Users/abidikshit/R_Projects/Data/counties.rds") 
head(counties)
```

```{r}
getwd()
setwd("/Users/abidikshit/R_Projects/Data/")
getwd()
```

```{r}
install.packages("maps")
install.packages("mapproj")
```

```{r}
library(shiny) 
library(maps) 
library(mapproj)
```

```{r}
source("helpers.R")
counties <- readRDS("/Users/abidikshit/R_Projects/Data/counties.rds")
```

```{r}
# User interface ----
ui <- fluidPage( titlePanel("censusVis"),
sidebarLayout( sidebarPanel(
 helpText("Create demographic maps with information from the 2010 US Census."),
selectInput("var",
label = "Choose a variable to display", choices = c("Percent White", "Percent Black",
"Percent Hispanic", "Percent Asian"),
 selected = "Percent White"),
sliderInput("range",
label = "Range of interest:",
min = 0, max = 100, value = c(0, 100)) ),
mainPanel(plotOutput("map")) )
)
# Server logic ----
server <- function(input, output) {
  output$map <- renderPlot({ 
    data <- switch(input$var,
                   "Percent White" = counties$white,
                   "Percent Black" = counties$black,
                   "Percent Hispanic" = counties$hispanic,
                   "Percent Asian" = counties$asian
                   )

percent_map(var = data, color = "darkblue", legend.title = "MyProject", max = 100, min = 10)
})

}
# Run app ---- shinyApp(ui, server)
shinyApp(ui, server)
```

